name: Automation ğŸ›ï¸

on:
  workflow_call:

jobs:
  conflicts:
    name: Merge conflict labeling ğŸ·ï¸
    runs-on: ubuntu-latest
    steps:
      - uses: eps1lon/actions-label-merge-conflict@1b1b1fcde06a9b3d089f3464c96417961dde1168 # v3.0.2
        with:
          dirtyLabel: 'merge conflict'
          commentOnDirty: 'This pull request has merge conflicts. Please resolve the conflicts so the PR can be successfully reviewed and merged.'
          repoToken: ${{ secrets.JF_BOT_TOKEN }}
