name: 'Automation'

on:
  push:
  pull_request_target:

jobs:
  triage:
    name: 'Merge conflict labeling'
    runs-on: ubuntu-latest
    steps:
      - uses: eps1lon/actions-label-merge-conflict@v2.0.1
        with:
          dirtyLabel: 'merge conflict'
          repoToken: ${{ secrets.JF_BOT_TOKEN }}
