name: 'Automation'

on:
  push:
    branches:
      - master
  pull_request_target:
    types:
      - synchronize

jobs:
  triage:
    name: 'Merge conflict labeling'
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'jellyfin/jellyfin-web' }}
    steps:
      - uses: eps1lon/actions-label-merge-conflict@fd1f295ee7443d13745804bc49fe158e240f6c6e # tag=v2.1.0
        with:
          dirtyLabel: 'merge conflict'
          repoToken: ${{ secrets.JF_BOT_TOKEN }}
