name: Build

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches: [ master, release* ]
  pull_request_target:
    branches: [ master, release* ]
  workflow_dispatch:

jobs:
  run-build-prod:
    name: Run production build
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Setup node environment
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: 20
          check-latest: true
          cache: npm

      - name: Install Node.js dependencies
        run: npm ci --no-audit

      - name: Run a production build
        env:
          JELLYFIN_VERSION: ${{ github.event.pull_request.head.sha || github.sha }}
        run: npm run build:production

      - name: Update config.json for testing
        run: |
          jq '.multiserver=true | .servers=["https://demo.jellyfin.org/unstable"]' dist/config.json > dist/config.tmp.json
          mv dist/config.tmp.json dist/config.json

      - name: Upload artifact
        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4.3.6
        with:
          name: jellyfin-web__prod
          path: dist

  publish:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'jellyfin/jellyfin-web' }}
    needs:
      - run-build-prod
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Add comment
        uses: thollander/actions-comment-pull-request@fabd468d3a1a0b97feee5f6b9e499eab0dd903f6 # v2.5.0
        if: ${{ github.event_name == 'pull_request_target' }}
        with:
          GITHUB_TOKEN: ${{ secrets.JF_BOT_TOKEN }}
          message: |
            ## Cloudflare Pages deployment

            | **Latest commit** | <code>${{ github.event.pull_request.head.sha || github.sha }}</code> |
            |-------------------|:-:|
            | **Status**        | üîÑ Deploying... |
            | **Preview URL**   | Not available |
            | **Type**          | üîÄ Preview |
          pr_number: ${{ github.event.pull_request.number }}
          comment_tag: CFPages-deployment
          mode: recreate

      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@09f2f74827fd3a8607589e5ad7f9398816f540fe # v3.1.4
        with:
          name: jellyfin-web__prod
          path: dist

      - name: Publish to Cloudflare
        id: cf
        uses: cloudflare/pages-action@f0a1cd58cd66095dee69bfa18fa5efd1dde93bca # v1.5.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: jellyfin-web
          branch: ${{ github.event.pull_request.head.ref || github.ref_name }}
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Update status comment (Success)
        if: ${{ github.event_name == 'pull_request_target' && success() }}
        uses: thollander/actions-comment-pull-request@fabd468d3a1a0b97feee5f6b9e499eab0dd903f6 # v2.5.0
        with:
          GITHUB_TOKEN: ${{ secrets.JF_BOT_TOKEN }}
          message: |
            ## Cloudflare Pages deployment

            | **Latest commit** | <code>${{ github.event.pull_request.head.sha || github.sha }}</code> |
            |-------------------|:-:|
            | **Status**        | ‚úÖ Deployed! |
            | **Preview URL**   | ${{ steps.cf.outputs.url != '' && steps.cf.outputs.url || 'Not available' }} |
            | **Type**          | üîÄ Preview |
          pr_number: ${{ github.event.pull_request.number }}
          comment_tag: CFPages-deployment
          mode: recreate

      - name: Update status comment (Failure)
        if: ${{ github.event_name == 'pull_request_target' && failure() }}
        uses: thollander/actions-comment-pull-request@fabd468d3a1a0b97feee5f6b9e499eab0dd903f6 # v2.5.0
        with:
          GITHUB_TOKEN: ${{ secrets.JF_BOT_TOKEN }}
          message: |
            ## Cloudflare Pages deployment

            | **Latest commit** | <code>${{ github.event.pull_request.head.sha || github.sha }}</code> |
            |-------------------|:-:|
            | **Status**        | ‚ùå Failure. Check workflow logs for details |
            | **Preview URL**   | Not available |
            | **Type**          | üîÄ Preview |
          pr_number: ${{ github.event.pull_request.number }}
          comment_tag: CFPages-deployment
          mode: recreate
