name: Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-eslint:
    name: Run eslint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Setup node environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12
          check-latest: true

      - name: Get npm cache directory path
        id: npm-cache-dir-path
        run: echo "::set-output name=dir::$(npm config get cache)"

      - name: Cache node_modules
        uses: actions/cache@v2.1.4
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install Node.js dependencies
        run: npm ci --no-audit
        env:
          SKIP_PREPARE: true

      - name: Run eslint
        run: npm run lint

  run-stylelint-css:
    name: Run stylelint (css)
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Setup node environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12
          check-latest: true

      - name: Get npm cache directory path
        id: npm-cache-dir-path
        run: echo "::set-output name=dir::$(npm config get cache)"

      - name: Cache node_modules
        uses: actions/cache@v2.1.4
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Set up stylelint matcher
        uses: xt0rted/stylelint-problem-matcher@v1

      - name: Install Node.js dependencies
        run: npm ci --no-audit
        env:
          SKIP_PREPARE: true

      - name: Run stylelint
        run: npm run stylelint:css

  run-stylelint-scss:
    name: Run stylelint (scss)
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Setup node environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12
          check-latest: true

      - name: Get npm cache directory path
        id: npm-cache-dir-path
        run: echo "::set-output name=dir::$(npm config get cache)"

      - name: Cache node_modules
        uses: actions/cache@v2.1.4
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Set up stylelint matcher
        uses: xt0rted/stylelint-problem-matcher@v1

      - name: Install Node.js dependencies
        run: npm ci --no-audit
        env:
          SKIP_PREPARE: true

      - name: Run stylelint
        run: npm run stylelint:scss
