name: PR suggestions

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.id || github.run_id }}
  cancel-in-progress: true

on:
  pull_request_target:
    branches: [ master, release* ]
    types:
      - synchronize

jobs:
  run-eslint:
    name: Run eslint suggestions
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup node environment
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 20
          check-latest: true
          cache: npm

      - name: Install Node.js dependencies
        run: npm ci --no-audit

      - name: Run eslint
        if: ${{ github.repository == 'jellyfin/jellyfin-web' }}
        uses: CatChen/eslint-suggestion-action@e54ff640f89e75196c0ba3a0f15cce37053d1d0b # v4.1.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
